server:
  port: 16181

gtfs:
  staticURL: testdata/gtfs/sofia-static.zip
  agency_id: SOFIA

gtfsrt:
  tripUpdatesURL: pbf-input/trip-updates-golden.pbf
  vehiclePositionsURL: pbf-input/vehicle-positions-golden.pbf
  serviceAlertsURL: pbf-input/alerts-golden.pbf
  readIntervalMS: 30000
  timeoutMS: 5000

converter:
  unscheduledTripIndicator: _
  callDistanceAlongRouteNumOfDigits: 3
  tripKeyStrategy: raw
